os:
  editCommand: 'nvim' # as an example 
  openCommand: 'code -rg {{filename}}'


gui:
  showIcons: true

git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
